  name: tests

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
      
  jobs:
    
    coverage:
      
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      # install dependencies
      - name: conan
        run: |
          pip install conan
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: install
        run: conan install --install-folder build .
      - name: gcovr
        run: pip install gcovr
      # build project
      - name: cmake generate
        run: cmake -S . -B build
      - name: cmake generate
        run: cmake --build build --target coverage
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
